# Generated by Django 6.0.3 on 2026-04-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='status',
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='condition',
            field=models.CharField(choices=[('ready', 'Ready'), ('washing', 'In Washing'), ('repair', 'Under Repair')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.category'),
        ),
    ]
