# Generated by Django 6.0.3 on 2026-04-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_category_remove_rentalitem_status_rentalitem_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='available_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='total_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='material_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in meters', max_digits=10),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.material')),
            ],
        ),
    ]
