# Generated by Django 5.2.7 on 2026-04-25 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_accessory_image_accessorysale_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='total_stock',
        ),
        migrations.CreateModel(
            name='PhysicalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('washing', 'In Washing'), ('repair', 'Under Repair'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='adminApp.rentalitem')),
            ],
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.physicalunit'),
        ),
    ]
