# Generated by Django 5.2.7 on 2026-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_remove_rentalitem_available_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='size',
        ),
        migrations.AddField(
            model_name='physicalunit',
            name='size',
            field=models.CharField(default='Free Size', max_length=20),
        ),
    ]
