# Generated by Django 5.2.7 on 2026-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_coupon_rename_discount_accessorysale_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingorder',
            name='fitting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stitchingorder',
            name='is_fitting_completed',
            field=models.BooleanField(default=False),
        ),
    ]
