# Generated by Django 5.2.7 on 2026-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_stitchingorder_fitting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stitchingorder',
            name='fitting_date',
        ),
        migrations.RemoveField(
            model_name='stitchingorder',
            name='is_fitting_completed',
        ),
    ]
