# Generated by Django 5.2.7 on 2026-04-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_password_enabled', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
