# Generated by Django 5.2.7 on 2026-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='damage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='deducted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='deposit_status',
            field=models.CharField(choices=[('held', 'Held'), ('refunded', 'Refunded'), ('deducted', 'Deducted'), ('partially_refunded', 'Partially Refunded')], default='held', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
