# Generated by Django 5.2.7 on 2026-06-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_rentalorder_damage_notes_rentalorder_deducted_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalItem',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='physicalunit',
            old_name='rental_item',
            new_name='product',
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_returned', models.BooleanField(default=False)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_status', models.CharField(choices=[('held', 'Held'), ('refunded', 'Refunded'), ('deducted', 'Deducted'), ('partially_refunded', 'Partially Refunded')], default='held', max_length=20)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deducted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='RentalOrder',
        ),
    ]
