# Generated by Django 5.2.7 on 2026-06-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_rename_rentalitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminApp.rentalbooking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.physicalunit')),
            ],
        ),
    ]
