# Generated by Django 5.2.7 on 2026-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0015_rentalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalunit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('washing', 'In Washing'), ('repair', 'Under Repair'), ('damaged', 'Damaged'), ('retired', 'Retired')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='is_returned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='rental_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='return_date',
            field=models.DateField(db_index=True),
        ),
    ]
