# Generated by Django 5.2.7 on 2026-06-18 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0016_alter_physicalunit_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='booking_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('PRE_BOOKING', 'Pre-Booking')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='status',
            field=models.CharField(choices=[('PRE_BOOKED', 'Pre-Booked'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='Alteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('expected_completion_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alterations', to='adminApp.rentalbooking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.product')),
                ('alteration_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminApp.alterationtype')),
            ],
        ),
    ]
