# Generated by Django 5.2.7 on 2026-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0017_alterationtype_rentalbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteration',
            name='alteration_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alteration',
            name='restore_after_return',
            field=models.BooleanField(default=False),
        ),
    ]
