# Generated by Django 5.2.7 on 2026-06-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0018_alteration_alteration_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alteration',
            name='alteration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminApp.alterationtype'),
        ),
    ]
