# Generated by Django 5.2.7 on 2026-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0019_alter_alteration_alteration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalunit',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='physicalunit',
            name='barcode_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
