# Generated by Django 5.2.7 on 2026-06-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0021_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='advance_paid',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='stitchingorder',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='stitchingorder',
            name='due_amount',
        ),
    ]
