# Generated by Django 5.2.7 on 2026-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0022_delete_transaction_remove_rentalbooking_advance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
