# Generated by Django 5.2.17 on 2026-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0023_rentalbooking_collected_at_rentalbooking_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
